### PR TITLE
v2.1 Tasks

### LINKED ISSUE #92: [PE-D][Tester F] Garbage inputs on "recipe" commands throw exceptions in the terminal
Perhaps it would be more elegant to indicate the exception with a more use friendly output like "sorry, your input is missing a field. The correct syntax is : <syntax> "

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: iantenkai/ped#1

### LINKED ISSUE #119: [PE-D][Tester F] "recipe random" gives recipes that contain allergens
After indicating ingredient "x" as an allergen using ```allergen add x```, it is still possible for the recipe returned by ```recipe random``` to contain ingredients the user is allergic too

**why it should be fixed:** this can be potentially dangerous to users, especially if someone is cooking for another person with the expectation that all their friend's allergies have been accounted for.

**steps to reproduce:** 
1. add several allergens with ``allergen add```
2. input ```recipe random``` until a recipe with an allergen is returned

**expected behaviour**:
Only recipes that do not contain allergens should be returned

**actual behaviour**:
It is possible for recipes containing allergens to be returned.

**suggested change**: modify ```recipe random```s method to check if the random recipe contains any allergens, and if it does, reroll for a different recipe.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: iantenkai/ped#5

### LINKED ISSUE #138: [TA] Code Review for Yi Da
- [ ] `RecipeList.java line 25`: Try refactoring this try statement into something a bit more easy to read. The nested function calls just make it a bit complex. Consider separating it out into variables & placing them in the try block. 
- [ ] In general, some of the classes don't have any JavaDoc comments at all. So maybe consider adding those? 

Good job with following all the coding standard requirements! 👍🏽

### PR DESCRIPTION
**Pull request by ngyida**
Refactor RecipeList constructor and add Javadocs. Closes #138.
Add check for allergen for Recipe Random.  Closes #119.
Update invalid command output for RecipeDetail, Possible and Random. Closes #92.

### CODE REVIEW

File: src/main/java/seedu/mealcompanion/command/recipe/RecipeRandomCommand.java [hunk 1]
```diff
@@ -40,9 +40,13 @@ public void execute(MealCompanionSession mealCompanionSession){
...
             Recipe recipe = recipes.getRecipe(index);
             mealCompanionSession.getUi().printMessage("A random recipe is chosen:");
+            if (hasAllergen(recipe, mealCompanionSession.getAllergens())) {
+                mealCompanionSession.getUi().printMessage("IMPORTANT: You are allergic to the ingredient(s) in this " +
+                        "recipe. Proceed with care or run command again to get a different random recipe.");
+            }
             mealCompanionSession.getUi().printMessage(recipe.toString());
         } catch (MealCompanionException e) {
-            mealCompanionSession.getUi().printMessage(String.valueOf(e));
+            mealCompanionSession.getUi().printMessage(e.getMessage());
```
Comment (EthanYidong) [inline src/main/java/seedu/mealcompanion/command/recipe/RecipeRandomCommand.java:49]: Would it make more sense to have a catch-all outside of the execute function to reduce the repetition of this line? Good fix for now, but something we should look into to avoid repetition.

**Review by EthanYidong — APPROVED** [review]

File: src/main/java/seedu/mealcompanion/command/recipe/RecipeRandomCommand.java (hunk 1 above)
Comment (ngyida) [reply src/main/java/seedu/mealcompanion/command/recipe/RecipeRandomCommand.java:49]: A catch-all on a higher level definitely helps to reduce repetition! Lets look into this idea in our next meeting.

**Comment by TJW0911** [comment]
Looks good
