### PR TITLE
Fix Code Quality Issues

### LINKED ISSUE #140: [TA] Code Review for Ethan
- [ ] `MealCompanionSession.java`: Names of constants should be all CAPS with underscore to separate words 
- [ ]  `CommandArguments.java`: The comments on lines 38 to 40 can just be written as a multi line comment rather than a couple of single line comments. 
- [ ] `IngredientDatabase.java`: Lines 23 to 28 are a bit difficult to read, especially because of the chained function calls. Consider separating the calls into multiple lines within the try block. 

Good job on following the requirements! 👍🏽

### PR DESCRIPTION
**Pull request by EthanYidong**
Closes #140

### CODE REVIEW

File: src/main/java/seedu/mealcompanion/recipe/IngredientDatabase.java [hunk 1]
```diff
@@ -20,7 +21,9 @@ public class IngredientDatabase {
     private IngredientDatabase() {
         this.knownIngredients = new HashMap<>();
         Gson gson = new Gson();
-        try (Reader reader = new InputStreamReader(this.getClass().getResourceAsStream("/ingredients.json"))) {
+        try {
+            InputStream ingredientData = this.getClass().getResourceAsStream("/ingredients.json");
+            Reader reader = new InputStreamReader(ingredientData);
```
Comment (ngyida) [inline src/main/java/seedu/mealcompanion/recipe/IngredientDatabase.java:26]: good change to make the code more readable

**Review by ngyida — APPROVED** [review]
